### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by HarshShirsath** [Revopoint/3DViewer#4]
Hello, 
I tried compiling the package 3DViewer.sln, resulting in a failed build and terminal process failed to launch. 
As I was able to generate the Visual Studio 2017 project. However, was not able to launch it.

I would be glad if anyone would help me out in this.

**Comment by Revopoint** [comment]
Please update the code and try compiling again. If there are still compilation errors, please provide the compilation error messages.
